### ISSUE TITLE
Verilator version on dashboard appears wrong

### ISSUE THREAD

**Issue by wsnyder** [SymbiFlow/sv-tests#1208]
The version on the dashboard for Verilator seems very old. This doesn't seem to correspond with either the pass/fails which suggest more recent (ignoring #1207 false fails),  or version in the third_party directory which is much more recent. Is there another version mis-installed on the dashboard generation machines?

![firefox_P70W4eIgmm](https://user-images.githubusercontent.com/1180685/102018679-ab86c380-3d3c-11eb-9173-4f4659fd74cb.png)

**Comment by tgorochowik** [comment]
The package that is used is downloaded from the anaconda repository. It looks as though we are not downloading the latest version for some reason:
https://anaconda.org/SymbiFlow/verilator/files?sort=ndownloads&sort_order=desc

**Comment by caryr** [comment]
iverilog also looks to be outdated. Though not as bad as verilator. I'm also not sure about the file names they show 10, but V10 was replaced with V11 stable a while ago. I really think you should be tracking devel since that is where all the new functionality appears. Our general rule is only bug fixes go into stable which likely makes it almost LTS except we don't guarantee support for a given time. The goal for stable is stability :-). We do unstable development in branches and only integrate into master when the test suite is clean.

**Comment by tgorochowik** [comment]
This should be fixed by #1240

**Comment by caryr** [comment]
I'm not certain how often the dashboard is updated, but based on test failures it looks like Icarus is still out of date. I did update both it and ivtest earlier this week in the repo and ivtest does reflect the latest changes, but not iverilog. Also the anaconda link/version for Icarus looks totally wonky.

**Comment by wsnyder** [comment]
Thanks for fixing, just a note I haven't closed this, as I have yet to see the updated version appear on the dashboard (which appears stuck for other reasons).

**Comment by wsnyder** [comment]
On today's dashboard version is good, thanks.
